Set up Julia depot in /tmp/ on ARCHER2
Works around an issue where using very large numbers of MPI processes
(>2048) caused Julia to take a very long time to start up.
https://discourse.julialang.org/t/speeding-up-julia-startup-with-mpi-using-scratch-space-to-mitigate-hdd-access-delay/128971

diff --git a/machines/archer/jobscript-postprocess-plotsjl.template b/machines/archer/jobscript-postprocess-plotsjl.template
--- a/machines/archer/jobscript-postprocess-plotsjl.template
+++ b/machines/archer/jobscript-postprocess-plotsjl.template
@@ -23,6 +23,14 @@ echo "post-processing (with original post_processing) RUNDIR $(date)"
 # Set this environment variable to avoid warning messages from Qt when running without a display
 export QT_QPA_PLATFORM=offscreen
 
-bin/julia -Jplots_postproc.so --project=plots_post_processing/ run_post_processing.jl RUNDIR
+if [ -e compute-node-temp.julia.tar.bz ]; then
+  # Distribute the tar'ed Julia depot to all compute nodes, saving it to the /tmp/ directory which lives in RAM.
+  sbcast --compress=none compute-node-temp.julia.tar.bz  /tmp/compute-node-temp.julia.tar.bz
+else
+  echo "compute-node-temp.julia.tar.bz but is required: run machines/machine_setup.sh to create it."
+  exit 1
+fi
+
+machines/archer/tmp-depot-wrapper.sh bin/julia -Jplots_postproc.so --project=plots_post_processing/ run_post_processing.jl RUNDIR
 
 echo "finished post-processing RUNDIR $(date)"
diff --git a/machines/archer/jobscript-postprocess.template b/machines/archer/jobscript-postprocess.template
--- a/machines/archer/jobscript-postprocess.template
+++ b/machines/archer/jobscript-postprocess.template
@@ -19,6 +19,15 @@ source julia.env
 export SRUN_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK
 
 echo "post-processing RUNDIR $(date)"
-bin/julia -Jmakie_postproc.so --project=makie_post_processing/ run_makie_post_processing.jl RUNDIR
+
+if [ -e compute-node-temp.julia.tar.bz ]; then
+  # Distribute the tar'ed Julia depot to all compute nodes, saving it to the /tmp/ directory which lives in RAM.
+  sbcast --compress=none compute-node-temp.julia.tar.bz  /tmp/compute-node-temp.julia.tar.bz
+else
+  echo "compute-node-temp.julia.tar.bz but is required: run machines/machine_setup.sh to create it."
+  exit 1
+fi
+
+machines/archer/tmp-depot-wrapper.sh bin/julia -Jmakie_postproc.so --project=makie_post_processing/ run_makie_post_processing.jl RUNDIR
 
 echo "finished post-processing RUNDIR $(date)"
diff --git a/machines/archer/jobscript-precompile-makie-post-processing.template b/machines/archer/jobscript-precompile-makie-post-processing.template
--- a/machines/archer/jobscript-precompile-makie-post-processing.template
+++ b/machines/archer/jobscript-precompile-makie-post-processing.template
@@ -22,6 +22,23 @@ export SRUN_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK
 
 echo "precompiling post-processing $(date)"
 
+# Create the Julia 'depot' in /tmp/$USER, which (on ARCHER2) lives in RAM locally on each compute node
+mkdir -p /tmp/$USER
+
+if [ -e compute-node-temp.julia.tar.bz ]; then
+  tar -xjf compute-node-temp.julia.tar.bz -C /tmp/$USER/
+else
+  echo "compute-node-temp.julia.tar.bz does not exist but is required: run machines/machine_setup.sh to create it."
+  exit 1
+fi
+
 bin/julia --project=makie_post_processing/ precompile-makie-post-processing.jl
+
+# Don't re-save the tar file, because it might overwrite one being created by
+# machines/machine-setup.sh.
+#tar cjf compute-node-temp.julia.tar.bz -C /tmp/$USER/ compute-node-temp.julia/
+
+# I think /tmp/ should be cleaned up automatically, but just in case, delete our temporary depot.
+rm -rf /tmp/$USER
 
 echo "finished! $(date)"
diff --git a/machines/archer/jobscript-run.template b/machines/archer/jobscript-run.template
--- a/machines/archer/jobscript-run.template
+++ b/machines/archer/jobscript-run.template
@@ -22,6 +22,14 @@ export SRUN_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK
 
 echo "running INPUTFILE $(date)"
 
-srun --distribution=block:block --hint=nomultithread --ntasks=$SLURM_NTASKS bin/julia -Jmoment_kinetics.so --project -O3 run_moment_kinetics.jl INPUTFILE
+if [ -e compute-node-temp.julia.tar.bz ]; then
+  # Distribute the tar'ed Julia depot to all compute nodes, saving it to the /tmp/ directory which lives in RAM.
+  sbcast --compress=none compute-node-temp.julia.tar.bz  /tmp/compute-node-temp.julia.tar.bz
+else
+  echo "compute-node-temp.julia.tar.bz but is required: run machines/machine_setup.sh to create it."
+  exit 1
+fi
+
+srun --distribution=block:block --hint=nomultithread --ntasks=$SLURM_NTASKS machines/archer/tmp-depot-wrapper.sh bin/julia -Jmoment_kinetics.so --project -O3 run_moment_kinetics.jl INPUTFILE
 
 echo "finished INPUTFILE $(date)"
