Copy node-local depot functionality from 'archer' to 'pitagora'
This functionality helps to reduce load on the cluster file system,
improving startup/compile performance.

diff --git a/machines/pitagora/jobscript-postprocess.template b/machines/pitagora/jobscript-postprocess.template
--- a/machines/pitagora/jobscript-postprocess.template
+++ b/machines/pitagora/jobscript-postprocess.template
@@ -19,6 +19,19 @@ source julia.env
 
 echo "post-processing RUNDIR $(date)"
 
-bin/julia -Jmakie_postproc.so --project=makie_post_processing/ run_makie_post_processing.jl RUNDIR
+if [ -e compute-node-temp.julia.tar.bz ]; then
+  # Distribute the tar'ed Julia depot to all compute nodes, saving it to the $TMPDIR directory which is local to each node.
+  sbcast --compress=none compute-node-temp.julia.tar.bz  $TMPDIR/compute-node-temp.julia.tar.bz
+
+  # Copy the julia directory (found from the name of the executable) and
+  # moment_kinetics.so to the compute nodes for efficiency.
+  cp -ra $(dirname $(dirname $(cat .julia_default.txt))) $TMPDIR/julia-dir
+  cp -a makie_postproc.so $TMPDIR/makie_postproc.so
+else
+  echo "compute-node-temp.julia.tar.bz does not exist but is required: run machines/machine_setup.sh to create it."
+  exit 1
+fi
+
+machines/pitagora/tmp-depot-wrapper.sh -Jmakie_postproc.so --project=makie_post_processing/ run_makie_post_processing.jl RUNDIR
 
 echo "finished post-processing RUNDIR $(date)"
