Copy node-local depot functionality from 'archer' to 'pitagora'
This functionality helps to reduce load on the cluster file system,
improving startup/compile performance.

diff --git a/machines/pitagora/jobscript-postprocess-plotsjl.template b/machines/pitagora/jobscript-postprocess-plotsjl.template
--- a/machines/pitagora/jobscript-postprocess-plotsjl.template
+++ b/machines/pitagora/jobscript-postprocess-plotsjl.template
@@ -22,6 +22,19 @@ echo "post-processing (with original post_processing) RUNDIR $(date)"
 # Set this environment variable to avoid warning messages from Qt when running without a display
 export QT_QPA_PLATFORM=offscreen
 
-bin/julia -Jplots_postproc.so --project=plots_post_processing/ run_post_processing.jl RUNDIR
+if [ -e compute-node-temp.julia.tar.bz ]; then
+  # Distribute the tar'ed Julia depot to all compute nodes, saving it to the $TMPDIR directory which is local to each node.
+  sbcast --compress=none compute-node-temp.julia.tar.bz  $TMPDIR/compute-node-temp.julia.tar.bz
+
+  # Copy the julia directory (found from the name of the executable) and
+  # moment_kinetics.so to the compute nodes for efficiency.
+  cp -ra $(dirname $(dirname $(cat .julia_default.txt))) $TMPDIR/julia-dir
+  cp -a plots_postproc.so $TMPDIR/plots_postproc.so
+else
+  echo "compute-node-temp.julia.tar.bz does not exist but is required: run machines/machine_setup.sh to create it."
+  exit 1
+fi
+
+machines/pitagora/tmp-depot-wrapper.sh -Jplots_postproc.so --project=plots_post_processing/ run_post_processing.jl RUNDIR
 
 echo "finished post-processing RUNDIR $(date)"
diff --git a/machines/pitagora/jobscript-precompile-no-run.template b/machines/pitagora/jobscript-precompile-no-run.template
--- a/machines/pitagora/jobscript-precompile-no-run.template
+++ b/machines/pitagora/jobscript-precompile-no-run.template
@@ -19,6 +19,25 @@ source julia.env
 
 echo "precompiling $(date)"
 
+# Create the Julia 'depot' in $TMPDIR/$USER, which is local to each node.
+mkdir -p $TMPDIR/$USER
+
+if [ -e compute-node-temp.julia.tar.bz ]; then
+  tar -xjf compute-node-temp.julia.tar.bz -C $TMPDIR/$USER/
+else
+  echo "compute-node-temp.julia.tar.bz does not exist but is required: run machines/machine_setup.sh to create it."
+  exit 1
+fi
+
+export JULIA_DEPOT_PATH=$TMPDIR/$USER/compute-node-temp.julia
+
 bin/julia -t 128 --project -O3 precompile-no-run.jl
+
+# Don't re-save the tar file, because it might overwrite one being created by
+# machines/machine-setup.sh (e.g. one with post-processing packages included).
+#tar cjf compute-node-temp.julia.tar.bz -C $TMPDIR/$USER/ compute-node-temp.julia/
+
+# I think $TMPDIR/ should be cleaned up automatically, but just in case, delete our temporary depot.
+rm -rf $TMPDIR/$USER
 
 echo "finished! $(date)"
diff --git a/machines/pitagora/jobscript-run.template b/machines/pitagora/jobscript-run.template
--- a/machines/pitagora/jobscript-run.template
+++ b/machines/pitagora/jobscript-run.template
@@ -20,6 +20,23 @@ source julia.env
 
 echo "running INPUTFILE $(date)"
 
-srun --hint=nomultithread --distribution=block:block -n $SLURM_NTASKS bin/julia -Jmoment_kinetics.so --project -O3 RUNSCRIPT INPUTFILE
+if [ -e compute-node-temp.julia.tar.bz ]; then
+  # Distribute the tar'ed Julia depot to all compute nodes, saving it to the $TMPDIR directory which is local to each node.
+  sbcast --compress=none compute-node-temp.julia.tar.bz  $TMPDIR/compute-node-temp.julia.tar.bz
+
+  # Copy the julia directory (found from the name of the executable) and
+  # moment_kinetics.so to the compute nodes for efficiency.
+  # sbcast only copies files, so (following hint from
+  # https://www.ch.cam.ac.uk/computing/slurm-usage) just use srun instead to
+  # copy the julia directory - we are probably not too worried about
+  # performance here, so should be fine.
+  srun --ntasks=NODES --tasks-per-node=1 cp -ra $(dirname $(dirname $(cat .julia_default.txt))) $TMPDIR/julia-dir
+  sbcast --compress=none moment_kinetics.so $TMPDIR/moment_kinetics.so
+else
+  echo "compute-node-temp.julia.tar.bz does not exist but is required: run machines/machine_setup.sh to create it."
+  exit 1
+fi
+
+srun --hint=nomultithread --distribution=block:block -n $SLURM_NTASKS machines/pitagora/tmp-depot-wrapper.sh $TMPDIR/$USER/julia-dir/bin/julia -J $TMPDIR/$USER/moment_kinetics.so --project -O3 RUNSCRIPT INPUTFILE
 
 echo "finished INPUTFILE $(date)"
